### ISSUE TITLE
can't start new background task if time elapsed is more than 3 minutes.

### ISSUE THREAD

**Issue by iNabarawy** [voyage11/Location#7]
Hi , Thanks for a great approach
I'm using your code , It works as expected when the app is run through xcode debugger , but when the app runs on it's own it is limited to 3 min only and then it crashes , I monitor successful location updates and updates to server through UILocalNotifications , after 3 minutes all background processes stop and the app crashes , what i found in the crash log is the following 
<BKNewProcess: 0x124e37c00; com.eventagrate.JAC; pid: 8442; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x124e37ae0> id: 8442-700206AD-3E22-4CB1-8551-6A3B5F5E4721 name: Called by JAC, from -[BackgroundTaskManager beginNewBackgroundTask] process: <BKNewProcess: 0x124e37c00; com.MYAPPUDID; pid: 8442; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:8442 preventSuspend  preventIdleSleep  preventSuspendOnSleep ,
    <BKProcessAssertion: 0x124d1a350> id: 8442-33C56A89-43AB-43D0-8F18-A8EAA1BC3C1F name: Called by MYAPP, from -[BackgroundTaskManager beginNewBackgroundTask] process: <BKNewProcess: 0x124e37c00; com.MYAPPUDID; pid: 8442; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:8442 preventSuspend  preventIdleSleep  preventSuspendOnSleep 
)}

I was wondering If this solution doesn't work anymore or if you have updated your code to handle this error ,
Thanks for your help

**Comment by thenopen** [comment]
I have got this error.

**Comment by XcodePro492** [comment]
Hi,
Same thing,
Happen to me, Did you find out any working solution?
Thanks.

**Comment by voyage11** [comment]
The maximum background time for iOS 6 and below is 10 minutes, the maximum background time for iOS 7 and above is 3 minutes. 

Before the 3 minutes background time expires, you will have to restart the location service. If you wait until after 3 minutes, the background time has expired, then the iOS will suspend all the background services for the app. During the suspended mode, You will not be able to do anything from the background anymore (unless you have the region monitoring or startMonitoringSignificantLocationChanges implemented, that would be another topic on its own.)

So, the maximum time for you to restart the location service is 2 minutes and 59 seconds. To play safe, I would set it at 2 minutes and 30 seconds.

**Comment by ajitam** [comment]
Hi, I have the same problem, I noticed that background tasks are increasing every minute and I get something like this:

```
started background task 3
ending background task with id -2
kept background task id 3
kept master background task id 1
```

but then after 3 minutes I get

```
background task 0 expired
```

In log I can't find there master background task **0** is started

*iphone 6, iOS 8*
